# -*- coding: utf-8 -*-
"""презентация.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ftvl3tUVzgjLuctZyXBw8zJXfJwV8Tt
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import re
import string

from google.colab import drive
drive.mount('/content/drive')

df_fake = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Fake.csv")
df_true = pd.read_csv("/content/drive/My Drive/Colab Notebooks/True.csv")
df_fake["label"] = 0
df_true["label"] = 1

df = pd.concat([df_fake, df_true], axis =0 )

df = df.drop_duplicates(subset=['title'])
df = df.drop(["subject","date","text"], axis = 1)
print(df['label'].value_counts())

df = df.sample(frac=1, random_state=42).reset_index(drop=True)
df

def count_words(text):
    words = re.findall(r'\b\w+\b', text)
    return len(words)
df['len']=df["title"].apply(count_words)
df.describe()

df=df.drop(df[df['len'] == 0].index)
df=df.reset_index(drop=True)
df



print( (df['len'] < 46).sum()/df.shape[0])

import pandas as pd
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))

# Кол-во бинов по 100 символов
max_len = df['len'].max()
bins = range(0, int(max_len) + 10, 10)  # шаг 100

# Построим гистограмму и получим значения
n, bins, patches = plt.hist(
    df['len'],

    edgecolor='black',
    color='purple',
    alpha=0.7,
    weights=[100 / len(df)] * len(df)  # Преобразуем в проценты
)


plt.xlabel('Количество слов')
plt.ylabel('Процент текстов (%)')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.xticks(bins, rotation=45)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))

# Максимальная длина слова
max_len = df['len'].max()
bins = range(0, int(max_len) + 2, 5)  # шаг 1, чтобы считать каждую длину слова отдельно

# Строим гистограмму
n, bins, patches = plt.hist(
    df['len'],
    bins=bins,
    edgecolor='black',
    color='purple',
    alpha=0.7
)

plt.xlabel('Длина текста(в словах)')
plt.ylabel('Количество текстов')
plt.title('Распределение текстов по длине')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.xticks(bins, rotation=45)
plt.tight_layout()
plt.show()

def wordopt(text):
    text = text.lower()
    text = re.sub('watch:', '', text)
    text = re.sub('breaking:', '', text)
    text = re.sub('just in:', '', text)
    text = re.sub('report:', '', text)
    text = re.sub('breaking news:', '', text)
    text = re.sub('flashback:', '', text)
    text = re.sub('busted:', '', text)
    text = re.sub('bombshell:', '', text)
    text = re.sub('sunday screening:', '', text)
    text = re.sub('update:', '', text)
    text = re.sub('revealed:', '', text)
    text = re.sub('not kidding:', '', text)

    text = re.sub('video:', '', text)
    text = re.sub('breaking bombshell:', '', text)
    text = re.sub('factbox:', '', text)
    text = re.sub('exclusive:', '', text)
    text = re.sub('highlights:', '', text)
    text = re.sub('timeline:', '', text)
    text = re.sub('instant view:', '', text)



    text=re.sub(r'\S*/\S*', '', text)
    text = re.sub('\(.*?\)', '', text)
    text = re.sub(r'^.*?watch:', '', text)
    text=re.sub(r'^.*?report:', '', text)
    text=re.sub(r'^.*?breaking:', '', text)
    text = re.sub('\[.*?\]', '', text)
    #text = re.sub("\\W"," ",text)
    text = re.sub('https?://\S+|www\.\S+', '', text)  #????
    text = re.sub('<.*?>+', '', text)
    #text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text
df['title'] = df['title'].apply(wordopt)



import pandas as pd

# Предположим, у тебя есть DataFrame `df` с колонкой 'text'
mask = df['title'].str.lower().str.contains('hillary', case=False, na=False)

# Показать строки, содержащие подстроку

matched_rows=df[df['label'] == 1]
matched_rows = matched_rows[mask]
print(f"🔍 Найдено строк: {len(matched_rows)}")
matched_rows

import pandas as pd
from collections import Counter
import re

# Фильтруем строки, содержащие двоеточие
mask = df['title'].str.contains(':', case=False, na=False)
titles_with_colon = df[mask]['title']

# Функция для извлечения слова перед двоеточием
def extract_before_colon(text):
    matches = re.findall(r'^([^:]+):', text)

    return matches

# Собираем все найденные слова
all_words_before_colon = []

for title in titles_with_colon:
    words = extract_before_colon(title)
    all_words_before_colon.extend(words)

# Считаем частоту
counter = Counter(all_words_before_colon)
top_common = counter.most_common(20)

# Выводим
print("🔍 Топ 20 подслов перед двоеточием:")
for word, count in top_common:
    print(f"{word}: {count}")

import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
import re

def extract_top_colon_starters(df, top_n=15):
    mask = df['title'].str.contains(':', case=False, na=False)
    titles_with_colon = df[mask]['title']

    def extract_before_colon(text):
        match = re.findall(r'^([^:]+):', text)
        return [m.strip() for m in match]  # 🔧 Удаляем пробелы вокруг

    all_words = []
    for title in titles_with_colon:
        words = extract_before_colon(title)
        all_words.extend(words)

    return Counter(all_words).most_common(top_n)

# Извлекаем топ слова
top_fake = extract_top_colon_starters(df_fake, top_n=15)
top_true = extract_top_colon_starters(df_true, top_n=15)

# Объединяем в один DataFrame
df_plot = pd.DataFrame({
    'word': [w for w, _ in top_fake + top_true],
    'count': [c for _, c in top_fake + top_true],
    'dataset': ['FAKE'] * len(top_fake) + ['REAL'] * len(top_true)
})

# Удалим дубликаты слов для корректного отображения
df_plot = df_plot.drop_duplicates(subset=['word', 'dataset'])

# Визуализация
plt.figure(figsize=(14, 7))
colors = {'FAKE': 'tomato', 'REAL': 'mediumseagreen'}

# Построим бруски рядом друг с другом
for label in df_plot['dataset'].unique():
    subset = df_plot[df_plot['dataset'] == label]
    plt.bar(subset['word'], subset['count'], label=label, alpha=0.8, color=colors[label])

plt.title('Топ 15 подслов перед ":" ', fontsize=14)
plt.xlabel('Подслово перед ":"', fontsize=12)
plt.ylabel('Частота появления', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split

# Сначала train+val vs test
x_temp, x_test, y_temp, y_test = train_test_split(
    df['title'], df['label'],
    test_size=0.2,
    stratify=df['label'],
    random_state=42
)

# Затем train vs val
x_train, x_val, y_train, y_val = train_test_split(
    x_temp, y_temp,
    test_size=0.25,  # 0.25 * 0.8 = 0.2 от общего
    stratify=y_temp,
    random_state=42
)

# Проверка размеров
print(f"Train: {len(x_train)}")
print(f"Validation: {len(x_val)}")
print(f"Test: {len(x_test)}")

print(y_val.value_counts())

print(df['label'].value_counts())

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Предположим, у тебя есть переменные: y_train, y_val, y_test

# Создадим DataFrame для визуализации
df_plot = pd.DataFrame({

    'train': pd.Series(y_train),
    'validation': pd.Series(y_val),
    'test': pd.Series(y_test),

})

# Преобразуем в "long-form" для Seaborn
df_melted = df_plot.melt(var_name='Split', value_name='Label')

plt.figure(figsize=(9, 5))
sns.set_style("whitegrid")
sns.set_palette("pastel")

# Построим countplot
sns.countplot(data=df_melted, x='Split', hue='Label')

plt.ylabel("Количество новостей")
plt.xlabel("Выборка")
plt.legend(title="Класс", loc="upper right")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Количество элементов
total = len(df['label'])
counts = df['label'].value_counts(normalize=True) * 100  # В процентах

plt.figure(figsize=(6, 4))
sns.set_style("whitegrid")
palette = {'0': 'firebrick', '1': 'limegreen'}


ax = sns.countplot(x=df['label'], palette=palette)

# Подписи в % над столбиками
for p in ax.patches:
    percent = (p.get_height() / total) * 100
    ax.annotate(f'{percent:.1f}%', (p.get_x() + p.get_width() / 2., p.get_height() + 1),
                ha='center', va='bottom', fontsize=10)

plt.xticks([0, 1], ['Fake (0)', 'True (1)'])
plt.xlabel("Класс")
plt.ylabel("Количество новостей")
plt.title("Распределение классов в датасете")
plt.tight_layout()
plt.show()

from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords

vectorization = TfidfVectorizer()
xv_train =  TfidfVectorizer(stop_words=list(stopwords.words('english')), max_df=0.9, min_df=5)
xv_test = vectorization.transform(x_test)

import nltk
nltk.download('stopwords')

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction import text
from nltk.corpus import stopwords
stop_words = text.ENGLISH_STOP_WORDS  # + свой список при необходимости
vectorizer = TfidfVectorizer(stop_words=list(stopwords.words('english')), max_df=0.9, min_df=5)
xv_train = vectorizer.fit_transform(x_train)
xv_test = vectorizer.transform(x_test)

xv_train[0]

# Разделяем на train/test
from sklearn.model_selection import train_test_split


# Кросс-валидация ТОЛЬКО на X_train
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
scores = cross_val_score(model, xv_train, y_train, cv=5)

print("Средняя точность на тренировке (кросс-валидация):", scores.mean())

# После этого — уже финальное обучение и тест
model.fit(xv_train, y_train)
test_score = model.score(xv_test, y_test)
print("Оценка на отложенном тесте:", test_score)

from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(xv_train,y_train)
pred_lr=LR.predict(xv_test)
LR.score(xv_test, y_test)

print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

from sklearn.metrics import classification_report, f1_score

# Предсказания уже есть:
# pred_lr = LR.predict(xv_test)

print("🔍 Logistic Regression classification report:")
print(classification_report(y_test, pred_lr))

f1 = f1_score(y_test, pred_lr, average='weighted')  # Или 'macro', 'micro' — зависит от задачи
print(f"✅ F1-score (weighted): {f1:.4f}")

from sklearn.metrics import classification_report, f1_score

# Предсказания уже есть:
# pred_lr = LR.predict(xv_test)

print("🔍 Logistic Regression classification report:")
print(classification_report(y_test, pred_lr))

f1 = f1_score(y_test, pred_lr, average='weighted')  # Или 'macro', 'micro' — зависит от задачи
print(f"✅ F1-score (weighted): {f1:.4f}")

pattern = r'^([a-zA-Z]+):'

# Находим все совпадения
matches = [re.match(pattern, text) for text in x_train]
prefixes = [match.group(1).lower() for match in matches if match]  # группируем без учёта регистра

# Считаем количество каждого префикса
prefix_counts = Counter(prefixes)

print("Количество строк с двоеточием в начале:", len(prefixes))
print("Распределение по префиксам:", prefix_counts)

import numpy as np
print(np.bincount(y_train))
print(np.bincount(y_test))

from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, pred_lr))
print(confusion_matrix(y_test, pred_lr))

from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, pred_lr))
print(confusion_matrix(y_test, pred_lr))

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, pred_lr)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=["Fake", "Real"], yticklabels=[ "Fake","Real"])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

from sklearn.model_selection import cross_val_score
cv_scores = cross_val_score(LR, xv_train, y_train, cv=5, scoring='f1_weighted')
print(f"📊 Cross-validated F1-score: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

feature_names = vectorization.get_feature_names_out()
coefficients = LR.coef_[0]

# Топ-20 слов для класса fake (1)
top_fake_idx = np.argsort(coefficients)[-20:]
# Топ-20 слов для real (0)
top_real_idx = np.argsort(coefficients)[:20]

print("\n🧪 Top 20 слов, указывающих на REAL:")
for idx in reversed(top_fake_idx):
    print(f"{feature_names[idx]}: {coefficients[idx]:.4f}")

print("\n📰 Top 20 слов, указывающих на FAKE:")
for idx in top_real_idx:
    print(f"{feature_names[idx]}: {coefficients[idx]:.4f}")

feature_names = vectorization.get_feature_names_out()
coefficients = LR.coef_[0]

# Топ-20 слов для класса fake (1)
top_fake_idx = np.argsort(coefficients)[-20:]
# Топ-20 слов для real (0)
top_real_idx = np.argsort(coefficients)[:20]

print("\n🧪 Top 20 слов, указывающих на REAL:")
for idx in reversed(top_fake_idx):
    print(f"{feature_names[idx]}: {coefficients[idx]:.4f}")

print("\n📰 Top 20 слов, указывающих на FAKE:")
for idx in top_real_idx:
    print(f"{feature_names[idx]}: {coefficients[idx]:.4f}")

import numpy as np
import matplotlib.pyplot as plt

# Получаем индексы самых "реальных" и "фейковых" признаков
top_fake_idx = np.argsort(coefficients)[-20:]
top_real_idx = np.argsort(coefficients)[:20]

# Слова и коэффициенты
top_fake_words = [(feature_names[i], coefficients[i]) for i in top_fake_idx]
top_real_words = [(feature_names[i], coefficients[i]) for i in top_real_idx]

# Объединяем и инвертируем коэффициенты для визуального контраста
words = [w for w, _ in reversed(top_fake_words)] + [w for w, _ in top_real_words]
values = [v for _, v in reversed(top_fake_words)] + [v for _, v in top_real_words]

colors = ['mediumseagreen'] * 20 + ['tomato'] * 20

# Визуализация
plt.figure(figsize=(12, 10))
plt.barh(words, values, color=colors)
plt.axvline(0, color='black', linewidth=0.8)
plt.xlabel('Вес слова')
plt.ylabel('Слово')
plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

feature_names = vectorizer.get_feature_names_out()
coefficients = LR.coef_[0]

# Топ-20 слов для класса fake (1)
top_fake_idx = np.argsort(coefficients)[-20:]
# Топ-20 слов для real (0)
top_real_idx = np.argsort(coefficients)[:20]

print("\n🧪 Top 20 слов, указывающих на REAL:")
for idx in reversed(top_fake_idx):
    print(f"{feature_names[idx]}: {coefficients[idx]:.4f}")

print("\n📰 Top 20 слов, указывающих на FAKE:")
for idx in top_real_idx:
    print(f"{feature_names[idx]}: {coefficients[idx]:.4f}")

import numpy as np
import matplotlib.pyplot as plt

# Получаем индексы самых "реальных" и "фейковых" признаков
top_fake_idx = np.argsort(coefficients)[-20:]
top_real_idx = np.argsort(coefficients)[:20]

# Слова и коэффициенты
top_fake_words = [(feature_names[i], coefficients[i]) for i in top_fake_idx]
top_real_words = [(feature_names[i], coefficients[i]) for i in top_real_idx]

# Объединяем и инвертируем коэффициенты для визуального контраста
words = [w for w, _ in reversed(top_fake_words)] + [w for w, _ in top_real_words]
values = [v for _, v in reversed(top_fake_words)] + [v for _, v in top_real_words]

colors = ['mediumseagreen'] * 20 + ['tomato'] * 20

# Визуализация
plt.figure(figsize=(12, 10))
plt.barh(words, values, color=colors)
plt.axvline(0, color='black', linewidth=0.8)
plt.xlabel('Вес признака (коэффициент логрегрессии)')
plt.ylabel('Признак (слово)')
plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

from sklearn.ensemble import RandomForestClassifier

DT = RandomForestClassifier(random_state=0)
DT.fit(xv_train, y_train)
pred_dt = DT.predict(xv_test)
DT.score(xv_test, y_test)

print(classification_report(y_test, pred_dt))

import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split

# Модели
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(n_estimators=100),
    "Gradient Boosting": GradientBoostingClassifier()
}

plt.figure(figsize=(10, 7))

for name, model in models.items():
    # Обучение
    model.fit(xv_train, y_train)

    # Предсказание вероятностей
    y_probs = model.predict_proba(xv_test)[:, 1]  # вероятности класса "1"

    # ROC кривая
    fpr, tpr, _ = roc_curve(y_test, y_probs)
    roc_auc = auc(fpr, tpr)

    # Отрисовка
    plt.plot(fpr, tpr, label=f"{name} (AUC = {roc_auc:.3f})")

# Настройки графика
plt.plot([0, 1], [0, 1], linestyle='--', color='gray')  # базовая линия
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC-кривые моделей')
plt.legend(loc='lower right')
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.metrics import RocCurveDisplay

# Модели
models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "Random Forest": RandomForestClassifier()
}

plt.figure(figsize=(10, 8))

for name, model in models.items():
    model.fit(xv_train, y_train)

    # Получаем вероятности (не предсказания классов, а вероятности принадлежности к классу 1)
    probs = model.predict_proba(xv_test)[:, 1]

    # ROC: вычисление FPR и TPR
    fpr, tpr, _ = roc_curve(y_test, probs)
    roc_auc = auc(fpr, tpr)

    # График
    plt.plot(fpr, tpr, label=f'{name} (AUC = {roc_auc:.2f})')

# Диагональ случайного выбора
plt.plot([0, 1], [0, 1], 'k--', label='Random Guess')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC-кривые для разных моделей')
plt.legend(loc='lower right')
plt.grid()
plt.show()

from sklearn.metrics import precision_recall_curve, average_precision_score

plt.figure(figsize=(10, 8))

for name, model in models.items():
    probs = model.predict_proba(xv_test)[:, 1]
    precision, recall, _ = precision_recall_curve(y_test, probs)
    avg_precision = average_precision_score(y_test, probs)

    plt.plot(recall, precision, label=f'{name} (AP = {avg_precision:.2f})')

plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve для моделей')
plt.legend(loc='upper right')
plt.grid()
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

for name, model in models.items():
    preds = model.predict(xv_test)
    cm = confusion_matrix(y_test, preds)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm)

    print(f"🔎 Confusion Matrix для {name}")
    disp.plot(cmap='Blues')
    plt.title(name)
    plt.show()

from sklearn.metrics import classification_report

for name, model in models.items():
    preds = model.predict(xv_test)

    print(f" Classification Report для {name}")
    print(classification_report(y_test, preds, digits=4))

"""------------------------------------------------"""

vectorizer = TextVectorization(max_tokens=20000,
                               output_sequence_length=600,
                               output_mode='int')
vectorizer.adapt(x_train.values.tolist())

vectorized_train_text = vectorizer(x_train.values)
vectorized_test_text = vectorizer(x_test.values)

def count_words(text):
    words = re.findall(r'\b\w+\b', text)
    return len(words)
df['len']=df["title"].apply(count_words)
df.describe()
df=df.drop(df[df['len'] == 0].index)
df=df.reset_index(drop=True)
df

df.describe()

LR = LogisticRegression()
LR.fit(vectorized_train_text,y_train)
pred_lr=LR.predict(vectorized_test_text)
LR.score(vectorized_test_text, y_test)

import numpy as np
from sklearn.linear_model import LogisticRegression
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization

# 1. Создание и настройка векторизатора
vectorizer = TextVectorization(
    max_tokens=100000,  # Увеличенный размер словаря
    output_sequence_length=600,  # Увеличенная длина текста
    output_mode='int',
    standardize='lower_and_strip_punctuation'
)

# 2. Обучение векторизатора
vectorizer.adapt(x_train.tolist())  # Убедимся, что передаем список строк

# 3. Преобразование текста в векторы
vectorized_train_text = vectorizer(x_train.tolist())
vectorized_test_text = vectorizer(x_test.tolist())

# 4. Преобразование в numpy-массив для sklearn
vectorized_train_text = np.array(vectorized_train_text)
vectorized_test_text = np.array(vectorized_test_text)

# 5. Обучение логистической регрессии
LR = LogisticRegression(max_iter=500)  # Увеличиваем число итераций для лучшей сходимости
LR.fit(vectorized_train_text, y_train)

# 6. Оценка модели
pred_lr = LR.predict(vectorized_test_text)
accuracy = LR.score(vectorized_test_text, y_test)

print(f"Accuracy: {accuracy:.4f}")

import numpy as np
from tensorflow.keras.layers import TextVectorization, Embedding
from sklearn.linear_model import LogisticRegression
import tensorflow as tf

# 1. Настроим векторизатор
vectorizer = TextVectorization(
    max_tokens=50000,  # Уменьшаем размер словаря (100000 → 50000)
    output_sequence_length=400,  # Уменьшаем длину последовательности (600 → 400)
    standardize='lower_and_strip_punctuation'
)
vectorizer.adapt(x_train.tolist())

# 2. Преобразуем тексты в последовательности индексов (разреженный тензор)
vectorized_train_text = vectorizer(np.array(x_train))
vectorized_test_text = vectorizer(np.array(x_test))

# 3. Создаем слой Embedding (без обучения)
embedding_layer = Embedding(input_dim=50000, output_dim=64, input_length=400)

# 4. Функция для обработки данных по частям (чтобы не перегружать память)
def get_embeddings(data, batch_size=512):
    num_samples = data.shape[0]
    embeddings = []

    for i in range(0, num_samples, batch_size):
        batch = data[i:i+batch_size]  # Берем небольшой кусок данных
        embedded_batch = embedding_layer(batch)  # Применяем Embedding
        averaged_batch = tf.reduce_mean(embedded_batch, axis=1)  # Усредняем эмбеддинги
        embeddings.append(averaged_batch.numpy())  # Конвертируем в numpy и сохраняем

    return np.vstack(embeddings)  # Склеиваем все части в один массив

# 5. Генерация эмбеддингов (по частям, без переполнения памяти)
embedded_train_text = get_embeddings(vectorized_train_text, batch_size=512)
embedded_test_text = get_embeddings(vectorized_test_text, batch_size=512)

# 6. Обучаем логистическую регрессию
LR = LogisticRegression(max_iter=500)
LR.fit(embedded_train_text, y_train)

# 7. Оценка модели
accuracy = LR.score(embedded_test_text, y_test)
print(f"Accuracy: {accuracy:.4f}")

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization, Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential

# 1. Настроим векторизатор
vectorizer = TextVectorization(
    max_tokens=100000,
    output_sequence_length=64,
    standardize='lower_and_strip_punctuation'
)

# 2. Обучаем векторизатор на обучающих данных
vectorizer.adapt(x_train.tolist())

# 3. Преобразуем тексты в последовательности индексов
vectorized_train_text = vectorizer(x_train.tolist())
vectorized_test_text = vectorizer(x_test.tolist())

# 4. Создаем модель с Embedding-слоем
model = Sequential([
    Embedding(input_dim=100000, output_dim=256, input_length=64),  # Эмбеддинг
     Dropout(0.3),
    Flatten(),  # Разворачиваем тензор в одномерный вектор
    Dense(1, activation='sigmoid')  # Классификатор
])

# 5. Компилируем модель
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 6. Обучаем модель
model.fit(vectorized_train_text, y_train, epochs=10, batch_size=64, validation_data=(vectorized_test_text, y_test))

# 7. Оцениваем точность
loss, accuracy = model.evaluate(vectorized_test_text, y_test)
print(f"Accuracy: {accuracy:.4f}")

#17 апреля преза

vectorized_val_text = vectorizer(x_val.tolist())
loss, accuracy = model.evaluate(vectorized_val_text, y_val)
print(f"Accuracy: {accuracy:.4f}")

from sklearn.metrics import classification_report

# Предсказания и округление до 0/1
y_pred_probs = model.predict(vectorized_val_text)
y_pred = (y_pred_probs > 0.5).astype(int)

# Отчет по метрикам
print(classification_report(y_val, y_pred, digits=4))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_val, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Fake', 'Real'])
disp.plot(cmap='Blues')
plt.title(" Confusion Matrix")
plt.show()

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization, Embedding, Flatten, Dense, LSTM,Dropout
from tensorflow.keras.models import Sequential

# 1. Настроим векторизатор
vectorizer = TextVectorization(
    max_tokens=100000,
    output_sequence_length=64,
    standardize='lower_and_strip_punctuation'
)

# 2. Обучаем векторизатор на обучающих данных
vectorizer.adapt(x_train.tolist())

# 3. Преобразуем тексты в последовательности индексов
vectorized_train_text = vectorizer(x_train.tolist())
vectorized_test_text = vectorizer(x_test.tolist())

# 4. Создаем модель с Embedding-слоем
model1 = Sequential([
    Embedding(input_dim=100000, output_dim=256, input_length=64),  # Эмбеддинг
    Dropout(0.3),
    LSTM(128),  # Рекуррентный слой
    Dropout(0.3),
    Dense(1, activation='sigmoid')  # Классификатор
])

# 5. Компилируем модель
model1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 6. Обучаем модель
model1.fit(vectorized_train_text, y_train, epochs=12, batch_size=64, validation_data=(vectorized_test_text, y_test))

# 7. Оцениваем точность
vectorized_val_text = vectorizer(x_val.tolist())
loss, accuracy = model1.evaluate(vectorized_val_text, y_val)
print(f"Accuracy: {accuracy:.4f}")

model1.fit(vectorized_train_text, y_train, epochs=1, batch_size=64, validation_data=(vectorized_test_text, y_test))

loss, accuracy = model1.evaluate(vectorized_val_text, y_val)
print(f"Accuracy: {accuracy:.4f}")

from sklearn.metrics import classification_report

# Предсказания и округление до 0/1
y_pred_probs = model1.predict(vectorized_val_text)
y_pred = (y_pred_probs > 0.5).astype(int)

# Отчет по метрикам
print(classification_report(y_val, y_pred, digits=4))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_val, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Fake', 'Real'])
disp.plot(cmap='Blues')
plt.title(" Confusion Matrix")
plt.show()

import tensorflow as tf
from tensorflow.keras.layers import (
    Input, Embedding, MultiHeadAttention, LayerNormalization,
    Dense, Dropout, GlobalAveragePooling1D
)
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import AdamW
from tensorflow.keras.regularizers import l2

# 1. Класс для позиционных эмбеддингов
class PositionalEmbedding(tf.keras.layers.Layer):
    def __init__(self, seq_length, embed_dim, **kwargs):
        super().__init__(**kwargs)
        self.seq_length = seq_length
        self.embed_dim = embed_dim
        self.pos_emb = tf.keras.layers.Embedding(
            input_dim=seq_length, output_dim=embed_dim
        )

    def call(self, x):
        positions = tf.range(start=0, limit=self.seq_length, delta=1)
        positions = tf.reshape(positions, (1, -1))
        pos_embeddings = self.pos_emb(positions)
        return x + pos_embeddings

    def get_config(self):
        config = super().get_config()
        config.update({
            "seq_length": self.seq_length,
            "embed_dim": self.embed_dim
        })
        return config

# 2. Transformer Encoder Block
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0.1):
    # Self-Attention
    x = MultiHeadAttention(
        num_heads=num_heads, key_dim=head_size
    )(inputs, inputs)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(inputs + x)  # Residual connection

    # Feed Forward Network
    y = Dense(ff_dim, activation="gelu")(x)  # GELU как в BERT
    y = Dense(inputs.shape[-1])(y)
    y = Dropout(dropout)(y)
    return LayerNormalization(epsilon=1e-6)(x + y)

# 3. Полная модель
def build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=128,
    num_heads=4,
    ff_dim=256,
    num_layers=4,
    dropout=0.1,
    l2_reg=1e-4
):
    inputs = Input(shape=(seq_length,))

    # Embedding + Positional
    x = Embedding(input_dim=max_tokens, output_dim=embed_dim)(inputs)
    x = PositionalEmbedding(seq_length, embed_dim)(x)

    # Transformer Blocks
    for _ in range(num_layers):
        x = transformer_encoder(x, embed_dim, num_heads, ff_dim, dropout)

    # Classifier
    x = GlobalAveragePooling1D()(x)
    outputs = Dense(
        1,
        activation="sigmoid",
        kernel_regularizer=l2(l2_reg)
    )(x)

    return Model(inputs=inputs, outputs=outputs)

# 4. Инициализация модели
model = build_transformer_model(
    max_tokens=100000,
    seq_length=64,
    embed_dim=128,
    num_heads=4,
    ff_dim=512,
    num_layers=4,
    dropout=0.1
)

# 5. AdamW с линейным затуханием LR
total_steps = len(x_train) // 32 * 5  # 5 эпох
lr_schedule = tf.keras.optimizers.schedules.PolynomialDecay(
    initial_learning_rate=5e-5,
    end_learning_rate=1e-6,
    decay_steps=total_steps
)
optimizer = AdamW(learning_rate=lr_schedule, weight_decay=1e-4)

# 6. Компиляция
model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 7. Обучение
history = model.fit(
    vectorized_train_text, y_train,
    epochs=5,
    batch_size=32,
    validation_data=(vectorized_test_text, y_test)
)

# 8. Оценка
loss, accuracy = model.evaluate(vectorized_val_text, y_val)
print(f"Accuracy: {accuracy:.4f}")

from sklearn.metrics import classification_report

# Предсказания и округление до 0/1
y_pred_probs = model.predict(vectorized_val_text)
y_pred = (y_pred_probs > 0.5).astype(int)

# Отчет по метрикам
print(classification_report(y_val, y_pred, digits=4))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_val, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Fake', 'Real'])
disp.plot(cmap='Blues')
plt.title(" Confusion Matrix")
plt.show()

history = model.fit(
    vectorized_train_text, y_train,
    epochs=5,
    batch_size=32,
    validation_data=(vectorized_test_text, y_test)
)

# 8. Оценка
loss, accuracy = model.evaluate(vectorized_val_text, y_val)
print(f"Accuracy: {accuracy:.4f}")

from sklearn.metrics import classification_report

# Предсказания и округление до 0/1
y_pred_probs = model.predict(vectorized_val_text)
y_pred = (y_pred_probs > 0.5).astype(int)

# Отчет по метрикам
print(classification_report(y_val, y_pred, digits=4))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_val, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Fake', 'Real'])
disp.plot(cmap='Blues')
plt.title(" Confusion Matrix")
plt.show()

history = model.fit(
    vectorized_train_text, y_train,
    epochs=2,
    batch_size=32,
    validation_data=(vectorized_test_text, y_test)
)

# 8. Оценка
loss, accuracy = model.evaluate(vectorized_val_text, y_val)
print(f"Accuracy: {accuracy:.4f}")
from sklearn.metrics import classification_report

# Предсказания и округление до 0/1
y_pred_probs = model.predict(vectorized_val_text)
y_pred = (y_pred_probs > 0.5).astype(int)

# Отчет по метрикам
print(classification_report(y_val, y_pred, digits=4))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_val, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Fake', 'Real'])
disp.plot(cmap='Blues')
plt.title(" Confusion Matrix")
plt.show()

"""старое"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization, Embedding, Dense, Input, MultiHeadAttention, LayerNormalization, GlobalAveragePooling1D, Dropout
from tensorflow.keras.models import Model

# 1. Настраиваем векторизатор (как у вас)
vectorizer = TextVectorization(
    max_tokens=100000,
    output_sequence_length=600,
    standardize='lower_and_strip_punctuation'
)
vectorizer.adapt(x_train.tolist())

# 2. Преобразуем тексты в последовательности
vectorized_train_text = vectorizer(x_train.tolist())
vectorized_test_text = vectorizer(x_test.tolist())

# 3. Создаём Transformer-модель
def build_transformer_model():
    inputs = Input(shape=(600,), dtype=tf.int32)  # input_length=600

    # Эмбеддинг + позиционное кодирование (упрощённо)
    x = Embedding(input_dim=100000, output_dim=128)(inputs)

    # Transformer Block
    x = MultiHeadAttention(num_heads=4, key_dim=128)(x, x)  # Self-Attention
    x = LayerNormalization(epsilon=1e-6)(x)
    x = Dropout(0.1)(x)

    # Усреднение по временной оси
    x = GlobalAveragePooling1D()(x)

    # Классификатор
    outputs = Dense(1, activation='sigmoid')(x)

    return Model(inputs=inputs, outputs=outputs)

model = build_transformer_model()

# 4. Компилируем
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 5. Обучаем
history = model.fit(
    vectorized_train_text, y_train,
    epochs=5,
    batch_size=32,
    validation_data=(vectorized_test_text, y_test)
)

# 6. Оценка
loss, accuracy = model.evaluate(vectorized_test_text, y_test)
print(f"Accuracy: {accuracy:.4f}")

import tensorflow as tf
from tensorflow.keras.layers import (
    Input, Embedding, MultiHeadAttention, LayerNormalization,
    Dense, Dropout, GlobalAveragePooling1D
)
from tensorflow.keras.models import Model

def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0.1):
    # Self-Attention
    x = MultiHeadAttention(
        num_heads=num_heads, key_dim=head_size
    )(inputs, inputs)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(inputs + x)  # Residual connection

    # Feed Forward Network
    y = Dense(ff_dim, activation="relu")(x)
    y = Dense(inputs.shape[-1])(y)  # Возвращаем исходную размерность
    y = Dropout(dropout)(y)
    return LayerNormalization(epsilon=1e-6)(x + y)  # Ещё residual

def build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=128,
    num_heads=4,
    ff_dim=256,
    num_layers=4,  # Количество Transformer-блоков
    dropout=0.1
):
    inputs = Input(shape=(seq_length,))

    # Embedding
    x = Embedding(input_dim=max_tokens, output_dim=embed_dim)(inputs)

    # Несколько Transformer-блоков
    for _ in range(num_layers):
        x = transformer_encoder(x, embed_dim, num_heads, ff_dim, dropout)

    # Классификатор
    x = GlobalAveragePooling1D()(x)
    outputs = Dense(1, activation="sigmoid")(x)

    return Model(inputs=inputs, outputs=outputs)

# Инициализация и обучение (как в предыдущем коде)
model = build_transformer_model(
    max_tokens=100000,
    num_layers=4,  # 4 блока как в BERT-base
    ff_dim=512     # Увеличенный размер FFN
)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(vectorized_train_text, y_train, epochs=5, batch_size=32,
          validation_data=(vectorized_test_text, y_test))

loss, accuracy = model.evaluate(vectorized_test_text, y_test)
print(f"Accuracy: {accuracy:.4f}")

import tensorflow as tf
from tensorflow.keras.layers import (
    Input, Embedding, MultiHeadAttention, LayerNormalization,
    Dense, Dropout, GlobalAveragePooling1D
)
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import AdamW
from tensorflow.keras.regularizers import l2

# 1. Класс для позиционных эмбеддингов
class PositionalEmbedding(tf.keras.layers.Layer):
    def __init__(self, seq_length, embed_dim):
        super().__init__()
        self.seq_length = seq_length
        self.embed_dim = embed_dim
        self.pos_emb = tf.keras.layers.Embedding(
            input_dim=seq_length, output_dim=embed_dim
        )

    def call(self, x):
        positions = tf.range(start=0, limit=self.seq_length, delta=1)
        positions = tf.reshape(positions, (1, -1))
        pos_embeddings = self.pos_emb(positions)
        return x + pos_embeddings

# 2. Transformer Encoder Block
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0.1):
    # Self-Attention
    x = MultiHeadAttention(
        num_heads=num_heads, key_dim=head_size
    )(inputs, inputs)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(inputs + x)  # Residual connection

    # Feed Forward Network
    y = Dense(ff_dim, activation="gelu")(x)  # GELU как в BERT
    y = Dense(inputs.shape[-1])(y)
    y = Dropout(dropout)(y)
    return LayerNormalization(epsilon=1e-6)(x + y)

# 3. Полная модель
def build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=128,
    num_heads=4,
    ff_dim=256,
    num_layers=4,
    dropout=0.1,
    l2_reg=1e-4
):
    inputs = Input(shape=(seq_length,))

    # Embedding + Positional
    x = Embedding(input_dim=max_tokens, output_dim=embed_dim)(inputs)
    x = PositionalEmbedding(seq_length, embed_dim)(x)

    # Transformer Blocks
    for _ in range(num_layers):
        x = transformer_encoder(x, embed_dim, num_heads, ff_dim, dropout)

    # Classifier
    x = GlobalAveragePooling1D()(x)
    outputs = Dense(
        1,
        activation="sigmoid",
        kernel_regularizer=l2(l2_reg)
    )(x)

    return Model(inputs=inputs, outputs=outputs)

# 4. Инициализация модели
model = build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=128,
    num_heads=4,
    ff_dim=512,
    num_layers=4,
    dropout=0.1
)

# 5. AdamW с линейным затуханием LR
total_steps = len(x_train) // 32 * 5  # 5 эпох
lr_schedule = tf.keras.optimizers.schedules.PolynomialDecay(
    initial_learning_rate=5e-5,
    end_learning_rate=1e-6,
    decay_steps=total_steps
)
optimizer = AdamW(learning_rate=lr_schedule, weight_decay=1e-4)

# 6. Компиляция
model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 7. Обучение
history = model.fit(
    vectorized_train_text, y_train,
    epochs=5,
    batch_size=32,
    validation_data=(vectorized_test_text, y_test)
)

# 8. Оценка
loss, accuracy = model.evaluate(vectorized_test_text, y_test)
print(f"Accuracy: {accuracy:.4f}")

# 2. Обучаем векторизатор на обучающих данных
from tensorflow.keras.layers import TextVectorization
vectorizer = TextVectorization(max_tokens=20000,
                               output_sequence_length=600,
                               output_mode='int')
vectorizer.adapt(x_train.tolist())

# 3. Преобразуем тексты в последовательности индексов
vectorized_train_text = vectorizer(x_train.tolist())
vectorized_test_text = vectorizer(x_test.tolist())

import tensorflow as tf
from tensorflow.keras.layers import (
    Input, Embedding, MultiHeadAttention, LayerNormalization,
    Dense, Dropout, GlobalAveragePooling1D
)
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import AdamW
from tensorflow.keras.regularizers import l2

# 1. Класс для позиционных эмбеддингов
class PositionalEmbedding(tf.keras.layers.Layer):
    def __init__(self, seq_length, embed_dim):
        super().__init__()
        self.seq_length = seq_length
        self.embed_dim = embed_dim
        self.pos_emb = tf.keras.layers.Embedding(
            input_dim=seq_length, output_dim=embed_dim
        )

    def call(self, x):
        positions = tf.range(start=0, limit=self.seq_length, delta=1)
        positions = tf.reshape(positions, (1, -1))
        pos_embeddings = self.pos_emb(positions)
        return x + pos_embeddings

# 2. Transformer Encoder Block
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0.1):
    # Self-Attention
    x = MultiHeadAttention(
        num_heads=num_heads, key_dim=head_size
    )(inputs, inputs)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(inputs + x)  # Residual connection

    # Feed Forward Network
    y = Dense(ff_dim, activation="gelu")(x)  # GELU как в BERT
    y = Dense(inputs.shape[-1])(y)
    y = Dropout(dropout)(y)
    return LayerNormalization(epsilon=1e-6)(x + y)

# 3. Полная модель
def build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=128,
    num_heads=4,
    ff_dim=256,
    num_layers=4,
    dropout=0.1,
    l2_reg=1e-4
):
    inputs = Input(shape=(seq_length,))

    # Embedding + Positional
    x = Embedding(input_dim=max_tokens, output_dim=embed_dim)(inputs)
    x = PositionalEmbedding(seq_length, embed_dim)(x)

    # Transformer Blocks
    for _ in range(num_layers):
        x = transformer_encoder(x, embed_dim, num_heads, ff_dim, dropout)

    # Classifier
    x = GlobalAveragePooling1D()(x)
    outputs = Dense(
        1,
        activation="sigmoid",
        kernel_regularizer=l2(l2_reg)
    )(x)

    return Model(inputs=inputs, outputs=outputs)

# 4. Инициализация модели
model = build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=128,
    num_heads=8,
    ff_dim=512,
    num_layers=4,
    dropout=0.1
)

# 5. AdamW с линейным затуханием LR
total_steps = len(x_train) // 32 * 5  # 5 эпох
lr_schedule = tf.keras.optimizers.schedules.PolynomialDecay(
    initial_learning_rate=5e-5,
    end_learning_rate=1e-6,
    decay_steps=total_steps
)
optimizer = AdamW(learning_rate=lr_schedule, weight_decay=1e-4)

# 6. Компиляция
model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 7. Обучение
history = model.fit(
    vectorized_train_text, y_train,
    epochs=5,
    batch_size=32,
    validation_data=(vectorized_test_text, y_test)
)

# 8. Оценка
loss, accuracy = model.evaluate(vectorized_test_text, y_test)
print(f"Accuracy: {accuracy:.4f}")

import tensorflow as tf
from tensorflow.keras.layers import (
    Input, Embedding, MultiHeadAttention, LayerNormalization,
    Dense, Dropout, GlobalAveragePooling1D
)
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import AdamW
from tensorflow.keras.regularizers import l2

# 1. Класс для позиционных эмбеддингов
class PositionalEmbedding(tf.keras.layers.Layer):
    def __init__(self, seq_length, embed_dim):
        super().__init__()
        self.seq_length = seq_length
        self.embed_dim = embed_dim
        self.pos_emb = tf.keras.layers.Embedding(
            input_dim=seq_length, output_dim=embed_dim
        )

    def call(self, x):
        positions = tf.range(start=0, limit=self.seq_length, delta=1)
        positions = tf.reshape(positions, (1, -1))
        pos_embeddings = self.pos_emb(positions)
        return x + pos_embeddings

# 2. Transformer Encoder Block
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0.1):
    # Self-Attention
    x = MultiHeadAttention(
        num_heads=num_heads, key_dim=head_size
    )(inputs, inputs)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(inputs + x)  # Residual connection

    # Feed Forward Network
    y = Dense(ff_dim, activation="gelu")(x)  # GELU как в BERT
    y = Dense(inputs.shape[-1])(y)
    y = Dropout(dropout)(y)
    return LayerNormalization(epsilon=1e-6)(x + y)

# 3. Полная модель
def build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=128,
    num_heads=8,
    ff_dim=256,
    num_layers=4,
    dropout=0.1,
    l2_reg=1e-4
):
    inputs = Input(shape=(seq_length,))

    # Embedding + Positional
    x = Embedding(input_dim=max_tokens, output_dim=embed_dim)(inputs)
    x = PositionalEmbedding(seq_length, embed_dim)(x)

    # Transformer Blocks
    for _ in range(num_layers):
        x = transformer_encoder(x, embed_dim, num_heads, ff_dim, dropout)

    # Classifier
    x = GlobalAveragePooling1D()(x)
    outputs = Dense(
        1,
        activation="sigmoid",
        kernel_regularizer=l2(l2_reg)
    )(x)

    return Model(inputs=inputs, outputs=outputs)

# 4. Инициализация модели
model = build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=256,
    num_heads=4,
    ff_dim=512,
    num_layers=4,
    dropout=0.1
)

# 5. AdamW с линейным затуханием LR
total_steps = len(x_train) // 32 * 5  # 5 эпох
lr_schedule = tf.keras.optimizers.schedules.PolynomialDecay(
    initial_learning_rate=5e-5,
    end_learning_rate=1e-6,
    decay_steps=total_steps
)
optimizer = AdamW(learning_rate=lr_schedule, weight_decay=1e-4)

# 6. Компиляция
model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 7. Обучение
history = model.fit(
    vectorized_train_text, y_train,
    epochs=5,
    batch_size=32,
    validation_data=(vectorized_test_text, y_test)
)

# 8. Оценка
loss, accuracy = model.evaluate(vectorized_test_text, y_test)
print(f"Accuracy: {accuracy:.4f}")

import tensorflow as tf
from tensorflow.keras.layers import (
    Input, Embedding, MultiHeadAttention, LayerNormalization,
    Dense, Dropout, GlobalAveragePooling1D
)
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import AdamW
from tensorflow.keras.regularizers import l2

# 1. Класс для позиционных эмбеддингов
class PositionalEmbedding(tf.keras.layers.Layer):
    def __init__(self, seq_length, embed_dim):
        super().__init__()
        self.seq_length = seq_length
        self.embed_dim = embed_dim
        self.pos_emb = tf.keras.layers.Embedding(
            input_dim=seq_length, output_dim=embed_dim
        )

    def call(self, x):
        positions = tf.range(start=0, limit=self.seq_length, delta=1)
        positions = tf.reshape(positions, (1, -1))
        pos_embeddings = self.pos_emb(positions)
        return x + pos_embeddings

# 2. Transformer Encoder Block
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0.1):
    # Self-Attention
    x = MultiHeadAttention(
        num_heads=num_heads, key_dim=head_size
    )(inputs, inputs)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(inputs + x)  # Residual connection

    # Feed Forward Network
    y = Dense(ff_dim, activation="gelu")(x)  # GELU как в BERT
    y = Dense(inputs.shape[-1])(y)
    y = Dropout(dropout)(y)
    return LayerNormalization(epsilon=1e-6)(x + y)

# 3. Полная модель
def build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=128,
    num_heads=4,
    ff_dim=256,
    num_layers=4,
    dropout=0.1,
    l2_reg=1e-4
):
    inputs = Input(shape=(seq_length,))

    # Embedding + Positional
    x = Embedding(input_dim=max_tokens, output_dim=embed_dim)(inputs)
    x = PositionalEmbedding(seq_length, embed_dim)(x)

    # Transformer Blocks
    for _ in range(num_layers):
        x = transformer_encoder(x, embed_dim, num_heads, ff_dim, dropout)

    # Classifier
    x = GlobalAveragePooling1D()(x)
    outputs = Dense(
        1,
        activation="sigmoid",
        kernel_regularizer=l2(l2_reg)
    )(x)

    return Model(inputs=inputs, outputs=outputs)

# 4. Инициализация модели
model = build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=512,
    num_heads=8,
    ff_dim=512,
    num_layers=4,
    dropout=0.1
)

# 5. AdamW с линейным затуханием LR
total_steps = len(x_train) // 32 * 5  # 5 эпох
lr_schedule = tf.keras.optimizers.schedules.PolynomialDecay(
    initial_learning_rate=5e-5,
    end_learning_rate=1e-6,
    decay_steps=total_steps
)
optimizer = AdamW(learning_rate=lr_schedule, weight_decay=1e-4)

# 6. Компиляция
model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 7. Обучение
history = model.fit(
    vectorized_train_text, y_train,
    epochs=5,
    batch_size=32,
    validation_data=(vectorized_test_text, y_test)
)

# 8. Оценка
loss, accuracy = model.evaluate(vectorized_test_text, y_test)
print(f"Accuracy: {accuracy:.4f}")

model.save_weights("transformer512.weights.h5")

from google.colab import drive
drive.mount('/content/drive')

a = pd.read_csv("/content/drive/My Drive/News_test_combined.csv")
b = pd.read_csv("/content/drive/My Drive/News_train_combined.csv")
df = pd.concat([a, b], axis =0 )
df

model.save_weights('/content/drive/My Drive/transformer512.weights.h5')

model = build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=512,
    num_heads=8,
    ff_dim=512,
    num_layers=4,
    dropout=0.1
)
total_steps = len(x_train) // 32 * 5  # 5 эпох
lr_schedule = tf.keras.optimizers.schedules.PolynomialDecay(
    initial_learning_rate=5e-5,
    end_learning_rate=1e-6,
    decay_steps=total_steps
)
optimizer = AdamW(learning_rate=lr_schedule, weight_decay=1e-4)

# 6. Компиляция
model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)
# Загрузка весов в модель
model.load_weights("transformer512.weights.h5")
loss, accuracy = model.evaluate(vectorized_test_text, y_test)
print(f"Accuracy: {accuracy:.4f}")

import tensorflow as tf
from tensorflow.keras.layers import (
    Input, Embedding, MultiHeadAttention, LayerNormalization,
    Dense, Dropout, GlobalAveragePooling1D
)
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import AdamW
from tensorflow.keras.regularizers import l2

# 1. Класс для позиционных эмбеддингов
class PositionalEmbedding(tf.keras.layers.Layer):
    def __init__(self, seq_length, embed_dim):
        super().__init__()
        self.seq_length = seq_length
        self.embed_dim = embed_dim
        self.pos_emb = tf.keras.layers.Embedding(
            input_dim=seq_length, output_dim=embed_dim
        )

    def call(self, x):
        positions = tf.range(start=0, limit=self.seq_length, delta=1)
        positions = tf.reshape(positions, (1, -1))
        pos_embeddings = self.pos_emb(positions)
        return x + pos_embeddings

# 2. Transformer Encoder Block
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0.1):
    # Self-Attention
    x = MultiHeadAttention(
        num_heads=num_heads, key_dim=head_size
    )(inputs, inputs)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(inputs + x)  # Residual connection

    # Feed Forward Network
    y = Dense(ff_dim, activation="gelu")(x)  # GELU как в BERT
    y = Dense(inputs.shape[-1])(y)
    y = Dropout(dropout)(y)
    return LayerNormalization(epsilon=1e-6)(x + y)

# 3. Полная модель
def build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=128,
    num_heads=4,
    ff_dim=256,
    num_layers=4,
    dropout=0.1,
    l2_reg=1e-4
):
    inputs = Input(shape=(seq_length,))

    # Embedding + Positional
    x = Embedding(input_dim=max_tokens, output_dim=embed_dim)(inputs)
    x = PositionalEmbedding(seq_length, embed_dim)(x)

    # Transformer Blocks
    for _ in range(num_layers):
        x = transformer_encoder(x, embed_dim, num_heads, ff_dim, dropout)

    # Classifier
    x = GlobalAveragePooling1D()(x)
    outputs = Dense(
        1,
        activation="sigmoid",
        kernel_regularizer=l2(l2_reg)
    )(x)

    return Model(inputs=inputs, outputs=outputs)

from tensorflow.keras.layers import TextVectorization
vectorizer = TextVectorization(
    max_tokens=100000,
    output_sequence_length=600,
    standardize='lower_and_strip_punctuation'
)
vectorizer.adapt(x_train.tolist())

# 2. Преобразуем тексты в последовательности
vectorized_train_text = vectorizer(x_train.tolist())
vectorized_test_text = vectorizer(x_test.tolist())

vectorized_test_text

model = build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=512,
    num_heads=8,
    ff_dim=512,
    num_layers=4,
    dropout=0.1
)
total_steps = len(x_train) // 32 * 5  # 5 эпох
lr_schedule = tf.keras.optimizers.schedules.PolynomialDecay(
    initial_learning_rate=5e-5,
    end_learning_rate=1e-6,
    decay_steps=total_steps
)
optimizer = AdamW(learning_rate=lr_schedule, weight_decay=1e-4)

# 6. Компиляция
model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)
# Загрузка весов в модель
model.load_weights("/content/drive/My Drive/transformer512.weights.h5")
loss, accuracy = model.evaluate(vectorized_test_text, y_test)
print(f"Accuracy: {accuracy:.4f}")

tt["text"] = tt["text"].apply(wordopt)
tt

vect_tt = vectorizer(tt["text"].tolist())

# Ваша строка для теста (обязательно в виде списка строк!)
test_strings = [
# 1. Векторизация текста
vectorized_text = vectorizer(test_strings)  # vectorizer ожидает список строк

# 2. Создаём "заглушку" для y_test (если метки неизвестны)
dummy_y =  [1]# Например, массив нулей той же длины
dummy_y = np.reshape(dummy_y, (-1, 1))
# 4. Оценка модели (если нужна accuracy)
loss, accuracy = model.evaluate(vect_tt, dummy_y)
print(f"Accuracy: {accuracy:.4f}")

tt=pd.read_csv("tt.csv")
tt

import pandas as pd

news_data = pd.DataFrame({
    'id': [1],

    'text': ['Сегодня Apple анонсировала революционный процессор M2...'],

})

news_data.to_csv('news_pandas.csv', index=False, encoding='utf-8')

import torch
from torch.utils.data import DataLoader, Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from tqdm import tqdm  # Progress bar

# Используем DistilBERT (он быстрее RoBERTa)
model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)
model.eval()  # Режим оценки (ускоряет инференс)

# PyTorch Dataset для батчевой обработки
class FakeNewsDataset(Dataset):
    def __init__(self, texts, labels):
        self.texts = texts
        self.labels = labels

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encodings = tokenizer(self.texts[idx], padding="max_length", truncation=True, max_length=256, return_tensors="pt")
        return {key: val.squeeze(0) for key, val in encodings.items()}, torch.tensor(self.labels[idx])

# DataLoader (обрабатываем данные частями)
batch_size = 32
test_dataset = FakeNewsDataset(x_test.tolist(), y_test.tolist())
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# Функция оценки модели с прогресс-баром
def evaluate(model, dataloader):
    correct = 0
    total = 0

    with torch.no_grad():
        for batch in tqdm(dataloader, desc="Processing Batches", unit="batch"):
            inputs, labels = batch
            outputs = model(**inputs)  # Вот тут тормозило
            predictions = torch.argmax(outputs.logits, dim=1)
            correct += (predictions == labels).sum().item()
            total += labels.size(0)

    return correct / total

# Оценка точности
accuracy = evaluate(model, test_loader)
print(f"Accuracy: {accuracy:.4f}")

"""### **Пытаемся убрать дубликаты новостей!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import re
import string

from google.colab import drive
drive.mount('/content/drive')

df_fake = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Fake.csv")
df_true = pd.read_csv("/content/drive/My Drive/Colab Notebooks/True.csv")

df_fake

df_true

df_fake = df_fake.drop_duplicates(subset=['text'])
df_fake

df_true = df_true.drop_duplicates(subset=['text'])
df_true

df_fake["label"] = 0
df_true["label"] = 1

df = pd.concat([df_fake, df_true], axis =0 )
df = df.drop(["title", "subject","date"], axis = 1)
df

df = df.sample(frac = 1)

df

df=df.drop(df[df['text'] == " "].index)
df.reset_index(inplace = True)
df

df.reset_index(inplace = True)
df.drop(["index"], axis = 1, inplace = True)
df

df_X=df["text"]
df_Y=df["label"]

import spacy
from tqdm.notebook import tqdm
en = spacy.load('en_core_web_sm')
def lemmatize(text):
    a = en(text)
    return ' '.join([token.lemma_ for token in a if
                  not token.is_stop])
tqdm.pandas()
df_X = df_X.progress_apply(lemmatize)

df = pd.concat([df_X.reset_index(drop=True),
                       df_Y.reset_index(drop=True)], axis=1)

df.to_csv('/content/drive/My Drive/DATA_NEWS.csv', index=False)

df=pd.read_csv('/content/drive/My Drive/DATA_NEWS.csv')

def wordopt(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W"," ",text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text
df["text"] = df["text"].apply(wordopt)

def count_words(text):
    words = re.findall(r'\b\w+\b', text)
    return len(words)
df['len']=df["text"].apply(count_words)

df=df.drop(df[df['len'] == 0].index)
df

df.reset_index(inplace = True)
df

x = df["text"]
y = df["label"]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

df.describe()

import pandas as pd

# Преобразуем в множества для быстрого сравнения
train_texts = set(x_train.dropna())
test_texts = set(x_test.dropna())

# Находим пересечения
exact_matches = train_texts & test_texts

print(f"Найдено {len(exact_matches)} точных совпадений:")
for match in list(exact_matches)[:5]:  # Выводим первые 5 примеров
    print(f"- {match[:100]}...")  # Обрезаем для удобства просмотра

# 2. Обучаем векторизатор на обучающих данных
from tensorflow.keras.layers import TextVectorization
vectorizer = TextVectorization(max_tokens=20000,
                               output_sequence_length=600,
                               output_mode='int')
vectorizer.adapt(x_train.tolist())

# 3. Преобразуем тексты в последовательности индексов
vectorized_train_text = vectorizer(x_train.tolist())
vectorized_test_text = vectorizer(x_test.tolist())

import tensorflow as tf
vectorizer_model = tf.keras.Sequential([vectorizer])
vectorizer_model.save("NEWtext_vectorizer_layer.keras")

import tensorflow as tf
from tensorflow.keras.layers import (
    Input, Embedding, MultiHeadAttention, LayerNormalization,
    Dense, Dropout, GlobalAveragePooling1D
)
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import AdamW
from tensorflow.keras.regularizers import l2

# 1. Класс для позиционных эмбеддингов
class PositionalEmbedding(tf.keras.layers.Layer):
    def __init__(self, seq_length, embed_dim):
        super().__init__()
        self.seq_length = seq_length
        self.embed_dim = embed_dim
        self.pos_emb = tf.keras.layers.Embedding(
            input_dim=seq_length, output_dim=embed_dim
        )

    def call(self, x):
        positions = tf.range(start=0, limit=self.seq_length, delta=1)
        positions = tf.reshape(positions, (1, -1))
        pos_embeddings = self.pos_emb(positions)
        return x + pos_embeddings

# 2. Transformer Encoder Block
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0.1):
    # Self-Attention
    x = MultiHeadAttention(
        num_heads=num_heads, key_dim=head_size
    )(inputs, inputs)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(inputs + x)  # Residual connection

    # Feed Forward Network
    y = Dense(ff_dim, activation="gelu")(x)  # GELU как в BERT
    y = Dense(inputs.shape[-1])(y)
    y = Dropout(dropout)(y)
    return LayerNormalization(epsilon=1e-6)(x + y)

# 3. Полная модель
def build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=128,
    num_heads=4,
    ff_dim=256,
    num_layers=4,
    dropout=0.1,
    l2_reg=1e-4
):
    inputs = Input(shape=(seq_length,))

    # Embedding + Positional
    x = Embedding(input_dim=max_tokens, output_dim=embed_dim)(inputs)
    x = PositionalEmbedding(seq_length, embed_dim)(x)

    # Transformer Blocks
    for _ in range(num_layers):
        x = transformer_encoder(x, embed_dim, num_heads, ff_dim, dropout)

    # Classifier
    x = GlobalAveragePooling1D()(x)
    outputs = Dense(
        1,
        activation="sigmoid",
        kernel_regularizer=l2(l2_reg)
    )(x)

    return Model(inputs=inputs, outputs=outputs)

# 4. Инициализация модели
model = build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=128,
    num_heads=4,
    ff_dim=512,
    num_layers=4,
    dropout=0.1
)

# 5. AdamW с линейным затуханием LR
total_steps = len(x_train) // 32 * 5  # 5 эпох
lr_schedule = tf.keras.optimizers.schedules.PolynomialDecay(
    initial_learning_rate=5e-5,
    end_learning_rate=1e-6,
    decay_steps=total_steps
)
optimizer = AdamW(learning_rate=lr_schedule, weight_decay=1e-4)

# 6. Компиляция
model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 7. Обучение
history = model.fit(
    vectorized_train_text, y_train,
    epochs=5,
    batch_size=32,
    validation_data=(vectorized_test_text, y_test)
)

# 8. Оценка
loss, accuracy = model.evaluate(vectorized_test_text, y_test)
print(f"Accuracy: {accuracy:.4f}")

import tensorflow as tf
from tensorflow.keras.layers import (
    Input, Embedding, MultiHeadAttention, LayerNormalization,
    Dense, Dropout, GlobalAveragePooling1D
)
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import AdamW
from tensorflow.keras.regularizers import l2

# 1. Класс для позиционных эмбеддингов
class PositionalEmbedding(tf.keras.layers.Layer):
    def __init__(self, seq_length, embed_dim, **kwargs):
        super().__init__(**kwargs)
        self.seq_length = seq_length
        self.embed_dim = embed_dim
        self.pos_emb = tf.keras.layers.Embedding(
            input_dim=seq_length, output_dim=embed_dim
        )

    def call(self, x):
        positions = tf.range(start=0, limit=self.seq_length, delta=1)
        positions = tf.reshape(positions, (1, -1))
        pos_embeddings = self.pos_emb(positions)
        return x + pos_embeddings

    def get_config(self):
        config = super().get_config()
        config.update({
            "seq_length": self.seq_length,
            "embed_dim": self.embed_dim
        })
        return config

# 2. Transformer Encoder Block
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0.1):
    # Self-Attention
    x = MultiHeadAttention(
        num_heads=num_heads, key_dim=head_size
    )(inputs, inputs)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(inputs + x)  # Residual connection

    # Feed Forward Network
    y = Dense(ff_dim, activation="gelu")(x)  # GELU как в BERT
    y = Dense(inputs.shape[-1])(y)
    y = Dropout(dropout)(y)
    return LayerNormalization(epsilon=1e-6)(x + y)

# 3. Полная модель
def build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=128,
    num_heads=4,
    ff_dim=256,
    num_layers=4,
    dropout=0.1,
    l2_reg=1e-4
):
    inputs = Input(shape=(seq_length,))

    # Embedding + Positional
    x = Embedding(input_dim=max_tokens, output_dim=embed_dim)(inputs)
    x = PositionalEmbedding(seq_length, embed_dim)(x)

    # Transformer Blocks
    for _ in range(num_layers):
        x = transformer_encoder(x, embed_dim, num_heads, ff_dim, dropout)

    # Classifier
    x = GlobalAveragePooling1D()(x)
    outputs = Dense(
        1,
        activation="sigmoid",
        kernel_regularizer=l2(l2_reg)
    )(x)

    return Model(inputs=inputs, outputs=outputs)

# 4. Инициализация модели
model = build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=128,
    num_heads=4,
    ff_dim=512,
    num_layers=4,
    dropout=0.1
)

# 5. AdamW с линейным затуханием LR
total_steps = len(x_train) // 32 * 5  # 5 эпох
lr_schedule = tf.keras.optimizers.schedules.PolynomialDecay(
    initial_learning_rate=5e-5,
    end_learning_rate=1e-6,
    decay_steps=total_steps
)
optimizer = AdamW(learning_rate=lr_schedule, weight_decay=1e-4)

# 6. Компиляция
model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 7. Обучение
history = model.fit(
    vectorized_train_text, y_train,
    epochs=5,
    batch_size=32,
    validation_data=(vectorized_test_text, y_test)
)

# 8. Оценка
loss, accuracy = model.evaluate(vectorized_test_text, y_test)
print(f"Accuracy: {accuracy:.4f}")

import tensorflow as tf
from tensorflow.keras.layers import (
    Input, Embedding, MultiHeadAttention, LayerNormalization,
    Dense, Dropout, GlobalAveragePooling1D
)
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import AdamW
from tensorflow.keras.regularizers import l2

# 1. Позиционные эмбеддинги (прямо в модели)
def add_positional_embeddings(x, seq_length, embed_dim):
    positions = tf.range(start=0, limit=seq_length, delta=1)
    positions = tf.reshape(positions, (1, -1))  # (1, seq_length)
    pos_emb = tf.keras.layers.Embedding(input_dim=seq_length, output_dim=embed_dim)(positions)
    return x + pos_emb  # Добавляем позиционные эмбеддинги к входным данным

# 2. Transformer Encoder Block
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0.1):
    # Self-Attention
    x = MultiHeadAttention(num_heads=num_heads, key_dim=head_size)(inputs, inputs)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(inputs + x)  # Residual connection

    # Feed Forward Network
    y = Dense(ff_dim, activation="gelu")(x)  # GELU как в BERT
    y = Dense(inputs.shape[-1])(y)
    y = Dropout(dropout)(y)
    return LayerNormalization(epsilon=1e-6)(x + y)

# 3. Полная модель
def build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=128,
    num_heads=4,
    ff_dim=256,
    num_layers=4,
    dropout=0.1,
    l2_reg=1e-4
):
    inputs = Input(shape=(seq_length,))

    # Embedding + Позиционные эмбеддинги
    x = Embedding(input_dim=max_tokens, output_dim=embed_dim)(inputs)
    x = add_positional_embeddings(x, seq_length, embed_dim)  # Добавляем позиционные эмбеддинги

    # Transformer Blocks
    for _ in range(num_layers):
        x = transformer_encoder(x, embed_dim, num_heads, ff_dim, dropout)

    # Classifier
    x = GlobalAveragePooling1D()(x)
    outputs = Dense(1, activation="sigmoid", kernel_regularizer=l2(l2_reg))(x)

    return Model(inputs=inputs, outputs=outputs)

# 4. Инициализация модели
model = build_transformer_model(
    max_tokens=100000,
    seq_length=600,
    embed_dim=128,
    num_heads=4,
    ff_dim=512,
    num_layers=4,
    dropout=0.1
)

# 5. AdamW с линейным затуханием LR
total_steps = len(x_train) // 32 * 5  # 5 эпох
lr_schedule = tf.keras.optimizers.schedules.PolynomialDecay(
    initial_learning_rate=5e-5,
    end_learning_rate=1e-6,
    decay_steps=total_steps
)
optimizer = AdamW(learning_rate=lr_schedule, weight_decay=1e-4)

# 6. Компиляция
model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 7. Обучение
history = model.fit(
    vectorized_train_text, y_train,
    epochs=5,
    batch_size=32,
    validation_data=(vectorized_test_text, y_test)
)

loss, accuracy = model.evaluate(vectorized_test_text, y_test)
print(f"Accuracy: {accuracy:.4f}")

# 8. Сохранение модели
import keras
model.save('/content/drive/My Drive/fake_news_model.h5')

# Сохранение векторизатора
keras.models.save_model(vectorizer, 'text_vectorizer_layer.keras')

model.save('/content/drive/My Drive/fake_news_model.keras')

vocab = vectorizer.get_vocabulary()

# Сохраняем его в текстовый файл
with open("vocab.txt", "w", encoding="utf-8") as f:
    for token in vocab:
        f.write(token + "\n")

model.save("/content/drive/My Drive/NWfake_news_model_fixed.h5")

model.save_weights("/content/drive/My Drive/NEW.weights.h5")

#для приложения
model.save('/content/drive/My Drive/fake_news_model.h5')

tt=pd.read_csv("tt.csv")
tt



import spacy

en = spacy.load('en_core_web_sm')
def lemmatize(text):
    a = en(text)
    return ' '.join([token.lemma_ for token in a if
                  not token.is_stop])

r = tt['text'].apply(lemmatize)
r=r.apply(wordopt)
r
#vectorized_test_text = vectorizer(.tolist())

vectorized_test_text = vectorizer(r.tolist())
y_test=[1]
yt=np.reshape(y_test, (-1, 1))

loss, accuracy = model.evaluate(vectorized_test_text, yt)
print(f"Accuracy: {accuracy:.4f}")

import keras

keras.models.save_model(vectorizer, 'text_vectorizer_layer.keras')

"""bert"""

import tensorflow as tf
import numpy as np
from tqdm import tqdm
from transformers import TFBertModel, BertTokenizer
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Dropout, GlobalAveragePooling1D, MultiHeadAttention, LayerNormalization
from tensorflow.keras.optimizers import Adam

bert_model = TFBertModel.from_pretrained("bert-base-uncased")
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
bert_model.trainable = False  # Заморозим веса

def tokenize_and_save(texts, labels, tokenizer, max_len, save_path="tokenized_data.npz"):
    input_ids = []
    attention_masks = []

    for text in tqdm(texts, desc="Tokenizing"):
        tokens = tokenizer(
            text,
            padding='max_length',
            truncation=True,
            max_length=max_len,
            return_tensors='tf'
        )
        input_ids.append(tokens['input_ids'][0])
        attention_masks.append(tokens['attention_mask'][0])

    input_ids = tf.stack(input_ids)
    attention_masks = tf.stack(attention_masks)

    # Сохраняем в файл
    np.savez_compressed(
        save_path,
        input_ids=input_ids.numpy(),
        attention_mask=attention_masks.numpy(),
        labels=np.array(labels)
    )

    print(f"✅ Сохранено в файл: {save_path}")
    return input_ids, attention_masks, labels

# 5. Токенизация и сохранение
max_len = 64
train_encodings, _, y_train = tokenize_and_save(x_train.tolist(), y_train, tokenizer, max_len, save_path="train_tokenized.npz")
test_encodings, _, y_test = tokenize_and_save(x_test.tolist(), y_test, tokenizer, max_len, save_path="test_tokenized.npz")
test_encodings, _, y_test = tokenize_and_save(x_val.tolist(), y_val, tokenizer, max_len, save_path="val_tokenized.npz")

from tensorflow.keras.layers import Layer
from transformers import TFBertModel
class BertEmbedding(Layer):
    def __init__(self, model_name="bert-base-uncased", **kwargs):
        super().__init__(**kwargs)
        self.bert = TFBertModel.from_pretrained(model_name)

    def call(self, inputs):
        return self.bert(inputs).last_hidden_state

max_len = 64
def load_tokenized(load_path="tokenized_data.npz"):
    data = np.load(load_path)
    input_ids = tf.convert_to_tensor(data['input_ids'])
    attention_mask = tf.convert_to_tensor(data['attention_mask'])
    labels = data['labels']
    print(f"📂 Загружено из файла: {load_path}")
    return input_ids, attention_mask, labels
# 6. Загрузка токенизированных данных (если нужно)
train_input_ids, train_attention_mask, y_train = load_tokenized("train_tokenized.npz")
test_input_ids, test_attention_mask, y_test = load_tokenized("test_tokenized.npz")
val_input_ids, val_attention_mask, y_val = load_tokenized("val_tokenized.npz")

# 7. Построение модели
def build_model(max_len, num_heads=4, ff_dim=256, num_layers=2, dropout=0.1):
    input_ids = Input(shape=(max_len,), dtype=tf.int32, name="input_ids")
    attention_mask = Input(shape=(max_len,), dtype=tf.int32, name="attention_mask")

    # Кастомный слой — теперь обходит ошибку с KerasTensor
    x = BertEmbedding()({"input_ids": input_ids, "attention_mask": attention_mask})

    for _ in range(num_layers):
        x = transformer_encoder(x, head_size=64, num_heads=num_heads, ff_dim=ff_dim, dropout=dropout)

    x = GlobalAveragePooling1D()(x)
    x = Dropout(dropout)(x)
    output = Dense(1, activation="sigmoid")(x)

    model = Model(inputs=[input_ids, attention_mask], outputs=output)
    return model




# 8. Компиляция и обучение модели
model = build_model(max_len=max_len)

model.compile(
    optimizer=Adam(learning_rate=2e-5),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 9. Обучение


model.fit(
    x={
        'input_ids': train_input_ids,
        'attention_mask': train_attention_mask
    },
    y=y_train,
    validation_data=(
        {
            'input_ids': test_input_ids,
            'attention_mask': test_attention_mask
        },
        y_test
    ),
    epochs=3,
    batch_size=32
)

model.save('/content/drive/My Drive/bert_model.keras')

model.save("/content/drive/My Drive/NWfake_news_model_fixed.h5")

# 10. Оценка
#qwerty
loss, acc = model.evaluate(
    {
        'input_ids': val_input_ids,
        'attention_mask': val_attention_mask
    },
    y_val
)
print(f"Test Accuracy: {acc:.4f}")

from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# 1. Предсказания на валидационной выборке
y_pred_probs = model.predict(
    {
        'input_ids': val_input_ids,
        'attention_mask': val_attention_mask
    },
    batch_size=32
)

# 2. Округляем вероятности в классы (0 или 1)
y_pred = (y_pred_probs.flatten() > 0.5).astype(int)

# 3. Выводим отчет по метрикам
print(classification_report(y_val, y_pred, digits=4))

# 4. Матрица ошибок
cm = confusion_matrix(y_val, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Fake', 'Real'])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

model.fit(
    x={
        'input_ids': train_input_ids,
        'attention_mask': train_attention_mask
    },
    y=y_train,
    validation_data=(
        {
            'input_ids': test_input_ids,
            'attention_mask': test_attention_mask
        },
        y_test
    ),
    epochs=3,
    batch_size=32
)

import pandas as pd

# Создаём DataFrame
df = pd.DataFrame({
    "text": ["Здравствуйте"],
    "label": [1]
})

# Сохраняем в CSV
df.to_csv("example.csv", index=False, encoding="utf-8-sig")

print("✅ Файл 'example.csv' создан.")

df.iloc[0].text=tt['text'].iloc[0]

df

tt

import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import Layer, Input, Dense, Dropout, GlobalAveragePooling1D, MultiHeadAttention, LayerNormalization
from transformers import TFBertModel
import numpy as np
# Кастомный слой с BERT
@tf.keras.utils.register_keras_serializable()
class BertEmbedding(Layer):
    def __init__(self, model_name="bert-base-uncased", **kwargs):
        super().__init__(**kwargs)
        self.bert = TFBertModel.from_pretrained(model_name)

    def call(self, inputs):
        return self.bert(inputs).last_hidden_state

# Кастомный encoder блок
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0.1):
    x = MultiHeadAttention(num_heads=num_heads, key_dim=head_size)(inputs, inputs)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(inputs + x)  # residual

    y = Dense(ff_dim, activation="gelu")(x)
    y = Dense(inputs.shape[-1])(y)
    y = Dropout(dropout)(y)
    return LayerNormalization(epsilon=1e-6)(x + y)

model = load_model(
    '/content/drive/My Drive/bert_model.keras',
    custom_objects={
        'BertEmbedding': BertEmbedding,
        'transformer_encoder': transformer_encoder
    }
)

model.save("/content/drive/My Drive/final_model.keras")

model.save('/content/drive/My Drive/newfinal_model.keras', save_format='keras')

def tokenize(texts, labels, tokenizer, max_len):
    input_ids = []
    attention_masks = []

    for text in texts:
        tokens = tokenizer(
            text,
            padding='max_length',
            truncation=True,
            max_length=max_len,
            return_tensors='np'  # ⬅️ вместо 'tf'
        )
        input_ids.append(tokens['input_ids'][0])
        attention_masks.append(tokens['attention_mask'][0])

    input_ids = np.stack(input_ids)
    attention_masks = np.stack(attention_masks)
    labels = np.array(labels)

    return input_ids, attention_masks, labels

tt=pd.read_csv("t2.csv")
tt

test_input_ids, test_attention_mask, y_test = tokenize(tt['text'].tolist(), tt['label'].tolist(), tokenizer, max_len=512)
loss, acc = model.evaluate(
    x={
        'input_ids': test_input_ids,
        'attention_mask': test_attention_mask
    },
    y=y_test
)
print(f"✅ Accuracy: {acc:.4f}")

max_len = 512
def load_tokenized(load_path="tokenized_data.npz"):
    data = np.load(load_path)
    input_ids = tf.convert_to_tensor(data['input_ids'])
    attention_mask = tf.convert_to_tensor(data['attention_mask'])
    labels = data['labels']
    print(f"📂 Загружено из файла: {load_path}")
    return input_ids, attention_mask, labels
test_input_ids, test_attention_mask, y_test = load_tokenized("/content/drive/My Drive/test_tokenized.npz")
loss, acc = model.evaluate(
    x={
        'input_ids': test_input_ids,
        'attention_mask': test_attention_mask
    },
    y=y_test
)
print(f"✅ Accuracy: {acc:.4f}")

